// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TicTacToeClient is the client API for TicTacToe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicTacToeClient interface {
	CreateLobby(ctx context.Context, in *CreateLobbyRequest, opts ...grpc.CallOption) (*CreateLobbyReply, error)
	JoinLobby(ctx context.Context, in *JoinLobbyRequest, opts ...grpc.CallOption) (*JoinLobbyReply, error)
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*Empty, error)
	MakeMoke(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*Empty, error)
	SubscribeGameUpdates(ctx context.Context, in *GameUpdateSubscription, opts ...grpc.CallOption) (TicTacToe_SubscribeGameUpdatesClient, error)
	SubscribeToGameCreation(ctx context.Context, in *LobbySubscription, opts ...grpc.CallOption) (TicTacToe_SubscribeToGameCreationClient, error)
}

type ticTacToeClient struct {
	cc grpc.ClientConnInterface
}

func NewTicTacToeClient(cc grpc.ClientConnInterface) TicTacToeClient {
	return &ticTacToeClient{cc}
}

func (c *ticTacToeClient) CreateLobby(ctx context.Context, in *CreateLobbyRequest, opts ...grpc.CallOption) (*CreateLobbyReply, error) {
	out := new(CreateLobbyReply)
	err := c.cc.Invoke(ctx, "/server.TicTacToe/CreateLobby", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticTacToeClient) JoinLobby(ctx context.Context, in *JoinLobbyRequest, opts ...grpc.CallOption) (*JoinLobbyReply, error) {
	out := new(JoinLobbyReply)
	err := c.cc.Invoke(ctx, "/server.TicTacToe/JoinLobby", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticTacToeClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.TicTacToe/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticTacToeClient) MakeMoke(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.TicTacToe/MakeMoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticTacToeClient) SubscribeGameUpdates(ctx context.Context, in *GameUpdateSubscription, opts ...grpc.CallOption) (TicTacToe_SubscribeGameUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &TicTacToe_ServiceDesc.Streams[0], "/server.TicTacToe/SubscribeGameUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticTacToeSubscribeGameUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TicTacToe_SubscribeGameUpdatesClient interface {
	Recv() (*GameUpdate, error)
	grpc.ClientStream
}

type ticTacToeSubscribeGameUpdatesClient struct {
	grpc.ClientStream
}

func (x *ticTacToeSubscribeGameUpdatesClient) Recv() (*GameUpdate, error) {
	m := new(GameUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ticTacToeClient) SubscribeToGameCreation(ctx context.Context, in *LobbySubscription, opts ...grpc.CallOption) (TicTacToe_SubscribeToGameCreationClient, error) {
	stream, err := c.cc.NewStream(ctx, &TicTacToe_ServiceDesc.Streams[1], "/server.TicTacToe/SubscribeToGameCreation", opts...)
	if err != nil {
		return nil, err
	}
	x := &ticTacToeSubscribeToGameCreationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TicTacToe_SubscribeToGameCreationClient interface {
	Recv() (*GameCreatedUpdate, error)
	grpc.ClientStream
}

type ticTacToeSubscribeToGameCreationClient struct {
	grpc.ClientStream
}

func (x *ticTacToeSubscribeToGameCreationClient) Recv() (*GameCreatedUpdate, error) {
	m := new(GameCreatedUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TicTacToeServer is the server API for TicTacToe service.
// All implementations must embed UnimplementedTicTacToeServer
// for forward compatibility
type TicTacToeServer interface {
	CreateLobby(context.Context, *CreateLobbyRequest) (*CreateLobbyReply, error)
	JoinLobby(context.Context, *JoinLobbyRequest) (*JoinLobbyReply, error)
	CreateGame(context.Context, *CreateGameRequest) (*Empty, error)
	MakeMoke(context.Context, *MoveRequest) (*Empty, error)
	SubscribeGameUpdates(*GameUpdateSubscription, TicTacToe_SubscribeGameUpdatesServer) error
	SubscribeToGameCreation(*LobbySubscription, TicTacToe_SubscribeToGameCreationServer) error
	mustEmbedUnimplementedTicTacToeServer()
}

// UnimplementedTicTacToeServer must be embedded to have forward compatible implementations.
type UnimplementedTicTacToeServer struct {
}

func (UnimplementedTicTacToeServer) CreateLobby(context.Context, *CreateLobbyRequest) (*CreateLobbyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLobby not implemented")
}
func (UnimplementedTicTacToeServer) JoinLobby(context.Context, *JoinLobbyRequest) (*JoinLobbyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinLobby not implemented")
}
func (UnimplementedTicTacToeServer) CreateGame(context.Context, *CreateGameRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedTicTacToeServer) MakeMoke(context.Context, *MoveRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeMoke not implemented")
}
func (UnimplementedTicTacToeServer) SubscribeGameUpdates(*GameUpdateSubscription, TicTacToe_SubscribeGameUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeGameUpdates not implemented")
}
func (UnimplementedTicTacToeServer) SubscribeToGameCreation(*LobbySubscription, TicTacToe_SubscribeToGameCreationServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToGameCreation not implemented")
}
func (UnimplementedTicTacToeServer) mustEmbedUnimplementedTicTacToeServer() {}

// UnsafeTicTacToeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicTacToeServer will
// result in compilation errors.
type UnsafeTicTacToeServer interface {
	mustEmbedUnimplementedTicTacToeServer()
}

func RegisterTicTacToeServer(s grpc.ServiceRegistrar, srv TicTacToeServer) {
	s.RegisterService(&TicTacToe_ServiceDesc, srv)
}

func _TicTacToe_CreateLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicTacToeServer).CreateLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.TicTacToe/CreateLobby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicTacToeServer).CreateLobby(ctx, req.(*CreateLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicTacToe_JoinLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicTacToeServer).JoinLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.TicTacToe/JoinLobby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicTacToeServer).JoinLobby(ctx, req.(*JoinLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicTacToe_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicTacToeServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.TicTacToe/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicTacToeServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicTacToe_MakeMoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicTacToeServer).MakeMoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.TicTacToe/MakeMoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicTacToeServer).MakeMoke(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicTacToe_SubscribeGameUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GameUpdateSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicTacToeServer).SubscribeGameUpdates(m, &ticTacToeSubscribeGameUpdatesServer{stream})
}

type TicTacToe_SubscribeGameUpdatesServer interface {
	Send(*GameUpdate) error
	grpc.ServerStream
}

type ticTacToeSubscribeGameUpdatesServer struct {
	grpc.ServerStream
}

func (x *ticTacToeSubscribeGameUpdatesServer) Send(m *GameUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _TicTacToe_SubscribeToGameCreation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LobbySubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TicTacToeServer).SubscribeToGameCreation(m, &ticTacToeSubscribeToGameCreationServer{stream})
}

type TicTacToe_SubscribeToGameCreationServer interface {
	Send(*GameCreatedUpdate) error
	grpc.ServerStream
}

type ticTacToeSubscribeToGameCreationServer struct {
	grpc.ServerStream
}

func (x *ticTacToeSubscribeToGameCreationServer) Send(m *GameCreatedUpdate) error {
	return x.ServerStream.SendMsg(m)
}

// TicTacToe_ServiceDesc is the grpc.ServiceDesc for TicTacToe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicTacToe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.TicTacToe",
	HandlerType: (*TicTacToeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLobby",
			Handler:    _TicTacToe_CreateLobby_Handler,
		},
		{
			MethodName: "JoinLobby",
			Handler:    _TicTacToe_JoinLobby_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _TicTacToe_CreateGame_Handler,
		},
		{
			MethodName: "MakeMoke",
			Handler:    _TicTacToe_MakeMoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeGameUpdates",
			Handler:       _TicTacToe_SubscribeGameUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToGameCreation",
			Handler:       _TicTacToe_SubscribeToGameCreation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server/tctxto.proto",
}
