// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: server/tctxto.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NavigationPath int32

const (
	NavigationPath_LOGIN    NavigationPath = 0
	NavigationPath_HOME     NavigationPath = 1
	NavigationPath_MY_LOBBY NavigationPath = 2
	NavigationPath_GAME     NavigationPath = 3
)

// Enum value maps for NavigationPath.
var (
	NavigationPath_name = map[int32]string{
		0: "LOGIN",
		1: "HOME",
		2: "MY_LOBBY",
		3: "GAME",
	}
	NavigationPath_value = map[string]int32{
		"LOGIN":    0,
		"HOME":     1,
		"MY_LOBBY": 2,
		"GAME":     3,
	}
)

func (x NavigationPath) Enum() *NavigationPath {
	p := new(NavigationPath)
	*p = x
	return p
}

func (x NavigationPath) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NavigationPath) Descriptor() protoreflect.EnumDescriptor {
	return file_server_tctxto_proto_enumTypes[0].Descriptor()
}

func (NavigationPath) Type() protoreflect.EnumType {
	return &file_server_tctxto_proto_enumTypes[0]
}

func (x NavigationPath) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NavigationPath.Descriptor instead.
func (NavigationPath) EnumDescriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{0}
}

type Mover int32

const (
	Mover_UNSPECIFIED Mover = 0
	Mover_X           Mover = 1
	Mover_O           Mover = 2
)

// Enum value maps for Mover.
var (
	Mover_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "X",
		2: "O",
	}
	Mover_value = map[string]int32{
		"UNSPECIFIED": 0,
		"X":           1,
		"O":           2,
	}
)

func (x Mover) Enum() *Mover {
	p := new(Mover)
	*p = x
	return p
}

func (x Mover) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mover) Descriptor() protoreflect.EnumDescriptor {
	return file_server_tctxto_proto_enumTypes[1].Descriptor()
}

func (Mover) Type() protoreflect.EnumType {
	return &file_server_tctxto_proto_enumTypes[1]
}

func (x Mover) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mover.Descriptor instead.
func (Mover) EnumDescriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{1}
}

type Winner int32

const (
	Winner_you   Winner = 0
	Winner_other Winner = 1
)

// Enum value maps for Winner.
var (
	Winner_name = map[int32]string{
		0: "you",
		1: "other",
	}
	Winner_value = map[string]int32{
		"you":   0,
		"other": 1,
	}
)

func (x Winner) Enum() *Winner {
	p := new(Winner)
	*p = x
	return p
}

func (x Winner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Winner) Descriptor() protoreflect.EnumDescriptor {
	return file_server_tctxto_proto_enumTypes[2].Descriptor()
}

func (Winner) Type() protoreflect.EnumType {
	return &file_server_tctxto_proto_enumTypes[2]
}

func (x Winner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Winner.Descriptor instead.
func (Winner) EnumDescriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{2}
}

type SubscriptionUpdateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to SubscriptionUpdateDataType:
	//	*SubscriptionUpdateData_NavigationUpdate
	//	*SubscriptionUpdateData_HandshakeReply
	//	*SubscriptionUpdateData_InvalidateReply
	//	*SubscriptionUpdateData_CreateLobbyReply
	//	*SubscriptionUpdateData_JoinLobbyReply
	//	*SubscriptionUpdateData_LeaveMyLobbyReply
	//	*SubscriptionUpdateData_MyLobbyDetails
	//	*SubscriptionUpdateData_MyLobbyJoinerUpdate
	//	*SubscriptionUpdateData_MyLobbyLeaverUpdate
	//	*SubscriptionUpdateData_CreateGameReply
	//	*SubscriptionUpdateData_MakeMoveReply
	//	*SubscriptionUpdateData_MoveUpdate
	//	*SubscriptionUpdateData_WinnerUpdate
	//	*SubscriptionUpdateData_DrawUpdate
	//	*SubscriptionUpdateData_GameStartUpdate
	//	*SubscriptionUpdateData_NextMoverUpdate
	//	*SubscriptionUpdateData_PlayerClientUpdate
	SubscriptionUpdateDataType isSubscriptionUpdateData_SubscriptionUpdateDataType `protobuf_oneof:"subscription_update_data_type"`
}

func (x *SubscriptionUpdateData) Reset() {
	*x = SubscriptionUpdateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionUpdateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionUpdateData) ProtoMessage() {}

func (x *SubscriptionUpdateData) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionUpdateData.ProtoReflect.Descriptor instead.
func (*SubscriptionUpdateData) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{0}
}

func (m *SubscriptionUpdateData) GetSubscriptionUpdateDataType() isSubscriptionUpdateData_SubscriptionUpdateDataType {
	if m != nil {
		return m.SubscriptionUpdateDataType
	}
	return nil
}

func (x *SubscriptionUpdateData) GetNavigationUpdate() *NavigationUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_NavigationUpdate); ok {
		return x.NavigationUpdate
	}
	return nil
}

func (x *SubscriptionUpdateData) GetHandshakeReply() *HandshakeReply {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_HandshakeReply); ok {
		return x.HandshakeReply
	}
	return nil
}

func (x *SubscriptionUpdateData) GetInvalidateReply() *InvalidateReply {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_InvalidateReply); ok {
		return x.InvalidateReply
	}
	return nil
}

func (x *SubscriptionUpdateData) GetCreateLobbyReply() *CreateLobbyReply {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_CreateLobbyReply); ok {
		return x.CreateLobbyReply
	}
	return nil
}

func (x *SubscriptionUpdateData) GetJoinLobbyReply() *JoinLobbyReply {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_JoinLobbyReply); ok {
		return x.JoinLobbyReply
	}
	return nil
}

func (x *SubscriptionUpdateData) GetLeaveMyLobbyReply() *LeaveMyLobbyReply {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_LeaveMyLobbyReply); ok {
		return x.LeaveMyLobbyReply
	}
	return nil
}

func (x *SubscriptionUpdateData) GetMyLobbyDetails() *MyLobbyDetails {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_MyLobbyDetails); ok {
		return x.MyLobbyDetails
	}
	return nil
}

func (x *SubscriptionUpdateData) GetMyLobbyJoinerUpdate() *MyLobbyJoinerUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_MyLobbyJoinerUpdate); ok {
		return x.MyLobbyJoinerUpdate
	}
	return nil
}

func (x *SubscriptionUpdateData) GetMyLobbyLeaverUpdate() *MyLobbyLeaverUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_MyLobbyLeaverUpdate); ok {
		return x.MyLobbyLeaverUpdate
	}
	return nil
}

func (x *SubscriptionUpdateData) GetCreateGameReply() *CreateGameReply {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_CreateGameReply); ok {
		return x.CreateGameReply
	}
	return nil
}

func (x *SubscriptionUpdateData) GetMakeMoveReply() *MakeMoveReply {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_MakeMoveReply); ok {
		return x.MakeMoveReply
	}
	return nil
}

func (x *SubscriptionUpdateData) GetMoveUpdate() *MoveUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_MoveUpdate); ok {
		return x.MoveUpdate
	}
	return nil
}

func (x *SubscriptionUpdateData) GetWinnerUpdate() *WinnerUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_WinnerUpdate); ok {
		return x.WinnerUpdate
	}
	return nil
}

func (x *SubscriptionUpdateData) GetDrawUpdate() *DrawUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_DrawUpdate); ok {
		return x.DrawUpdate
	}
	return nil
}

func (x *SubscriptionUpdateData) GetGameStartUpdate() *GameStartUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_GameStartUpdate); ok {
		return x.GameStartUpdate
	}
	return nil
}

func (x *SubscriptionUpdateData) GetNextMoverUpdate() *NextMoverUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_NextMoverUpdate); ok {
		return x.NextMoverUpdate
	}
	return nil
}

func (x *SubscriptionUpdateData) GetPlayerClientUpdate() *PlayerClientUpdate {
	if x, ok := x.GetSubscriptionUpdateDataType().(*SubscriptionUpdateData_PlayerClientUpdate); ok {
		return x.PlayerClientUpdate
	}
	return nil
}

type isSubscriptionUpdateData_SubscriptionUpdateDataType interface {
	isSubscriptionUpdateData_SubscriptionUpdateDataType()
}

type SubscriptionUpdateData_NavigationUpdate struct {
	NavigationUpdate *NavigationUpdate `protobuf:"bytes,1,opt,name=navigation_update,json=navigationUpdate,proto3,oneof"`
}

type SubscriptionUpdateData_HandshakeReply struct {
	HandshakeReply *HandshakeReply `protobuf:"bytes,2,opt,name=handshake_reply,json=handshakeReply,proto3,oneof"`
}

type SubscriptionUpdateData_InvalidateReply struct {
	InvalidateReply *InvalidateReply `protobuf:"bytes,3,opt,name=invalidate_reply,json=invalidateReply,proto3,oneof"`
}

type SubscriptionUpdateData_CreateLobbyReply struct {
	CreateLobbyReply *CreateLobbyReply `protobuf:"bytes,4,opt,name=create_lobby_reply,json=createLobbyReply,proto3,oneof"`
}

type SubscriptionUpdateData_JoinLobbyReply struct {
	JoinLobbyReply *JoinLobbyReply `protobuf:"bytes,5,opt,name=join_lobby_reply,json=joinLobbyReply,proto3,oneof"`
}

type SubscriptionUpdateData_LeaveMyLobbyReply struct {
	LeaveMyLobbyReply *LeaveMyLobbyReply `protobuf:"bytes,6,opt,name=leave_my_lobby_reply,json=leaveMyLobbyReply,proto3,oneof"`
}

type SubscriptionUpdateData_MyLobbyDetails struct {
	MyLobbyDetails *MyLobbyDetails `protobuf:"bytes,7,opt,name=my_lobby_details,json=myLobbyDetails,proto3,oneof"`
}

type SubscriptionUpdateData_MyLobbyJoinerUpdate struct {
	MyLobbyJoinerUpdate *MyLobbyJoinerUpdate `protobuf:"bytes,8,opt,name=my_lobby_joiner_update,json=myLobbyJoinerUpdate,proto3,oneof"`
}

type SubscriptionUpdateData_MyLobbyLeaverUpdate struct {
	MyLobbyLeaverUpdate *MyLobbyLeaverUpdate `protobuf:"bytes,9,opt,name=my_lobby_leaver_update,json=myLobbyLeaverUpdate,proto3,oneof"`
}

type SubscriptionUpdateData_CreateGameReply struct {
	CreateGameReply *CreateGameReply `protobuf:"bytes,10,opt,name=create_game_reply,json=createGameReply,proto3,oneof"`
}

type SubscriptionUpdateData_MakeMoveReply struct {
	MakeMoveReply *MakeMoveReply `protobuf:"bytes,11,opt,name=make_move_reply,json=makeMoveReply,proto3,oneof"`
}

type SubscriptionUpdateData_MoveUpdate struct {
	MoveUpdate *MoveUpdate `protobuf:"bytes,12,opt,name=move_update,json=moveUpdate,proto3,oneof"`
}

type SubscriptionUpdateData_WinnerUpdate struct {
	WinnerUpdate *WinnerUpdate `protobuf:"bytes,13,opt,name=winner_update,json=winnerUpdate,proto3,oneof"`
}

type SubscriptionUpdateData_DrawUpdate struct {
	DrawUpdate *DrawUpdate `protobuf:"bytes,14,opt,name=draw_update,json=drawUpdate,proto3,oneof"`
}

type SubscriptionUpdateData_GameStartUpdate struct {
	GameStartUpdate *GameStartUpdate `protobuf:"bytes,15,opt,name=game_start_update,json=gameStartUpdate,proto3,oneof"`
}

type SubscriptionUpdateData_NextMoverUpdate struct {
	NextMoverUpdate *NextMoverUpdate `protobuf:"bytes,16,opt,name=next_mover_update,json=nextMoverUpdate,proto3,oneof"`
}

type SubscriptionUpdateData_PlayerClientUpdate struct {
	PlayerClientUpdate *PlayerClientUpdate `protobuf:"bytes,17,opt,name=player_client_update,json=playerClientUpdate,proto3,oneof"`
}

func (*SubscriptionUpdateData_NavigationUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_HandshakeReply) isSubscriptionUpdateData_SubscriptionUpdateDataType() {}

func (*SubscriptionUpdateData_InvalidateReply) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_CreateLobbyReply) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_JoinLobbyReply) isSubscriptionUpdateData_SubscriptionUpdateDataType() {}

func (*SubscriptionUpdateData_LeaveMyLobbyReply) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_MyLobbyDetails) isSubscriptionUpdateData_SubscriptionUpdateDataType() {}

func (*SubscriptionUpdateData_MyLobbyJoinerUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_MyLobbyLeaverUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_CreateGameReply) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_MakeMoveReply) isSubscriptionUpdateData_SubscriptionUpdateDataType() {}

func (*SubscriptionUpdateData_MoveUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {}

func (*SubscriptionUpdateData_WinnerUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {}

func (*SubscriptionUpdateData_DrawUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {}

func (*SubscriptionUpdateData_GameStartUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_NextMoverUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

func (*SubscriptionUpdateData_PlayerClientUpdate) isSubscriptionUpdateData_SubscriptionUpdateDataType() {
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{1}
}

type Outcome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok           bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorCode    int32  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{2}
}

func (x *Outcome) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Outcome) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *Outcome) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Lobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Players []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *Lobby) Reset() {
	*x = Lobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lobby) ProtoMessage() {}

func (x *Lobby) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lobby.ProtoReflect.Descriptor instead.
func (*Lobby) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{3}
}

func (x *Lobby) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lobby) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExchangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type ExchangeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *ExchangeReply) Reset() {
	*x = ExchangeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeReply) ProtoMessage() {}

func (x *ExchangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeReply.ProtoReflect.Descriptor instead.
func (*ExchangeReply) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{6}
}

func (x *ExchangeReply) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type MyLobbyDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lobby *Lobby `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
}

func (x *MyLobbyDetails) Reset() {
	*x = MyLobbyDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyLobbyDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyLobbyDetails) ProtoMessage() {}

func (x *MyLobbyDetails) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyLobbyDetails.ProtoReflect.Descriptor instead.
func (*MyLobbyDetails) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{7}
}

func (x *MyLobbyDetails) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type MyLobbyJoinerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *MyLobbyJoinerUpdate) Reset() {
	*x = MyLobbyJoinerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyLobbyJoinerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyLobbyJoinerUpdate) ProtoMessage() {}

func (x *MyLobbyJoinerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyLobbyJoinerUpdate.ProtoReflect.Descriptor instead.
func (*MyLobbyJoinerUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{8}
}

func (x *MyLobbyJoinerUpdate) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type MyLobbyLeaverUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *MyLobbyLeaverUpdate) Reset() {
	*x = MyLobbyLeaverUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyLobbyLeaverUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyLobbyLeaverUpdate) ProtoMessage() {}

func (x *MyLobbyLeaverUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyLobbyLeaverUpdate.ProtoReflect.Descriptor instead.
func (*MyLobbyLeaverUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{9}
}

func (x *MyLobbyLeaverUpdate) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type LeaveMyLobbyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outcome *Outcome `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *LeaveMyLobbyReply) Reset() {
	*x = LeaveMyLobbyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveMyLobbyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMyLobbyReply) ProtoMessage() {}

func (x *LeaveMyLobbyReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMyLobbyReply.ProtoReflect.Descriptor instead.
func (*LeaveMyLobbyReply) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveMyLobbyReply) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

type JoinLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyId string `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{11}
}

func (x *JoinLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type JoinLobbyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outcome *Outcome `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *JoinLobbyReply) Reset() {
	*x = JoinLobbyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLobbyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyReply) ProtoMessage() {}

func (x *JoinLobbyReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyReply.ProtoReflect.Descriptor instead.
func (*JoinLobbyReply) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{12}
}

func (x *JoinLobbyReply) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

type InvalidateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outcome *Outcome `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *InvalidateReply) Reset() {
	*x = InvalidateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateReply) ProtoMessage() {}

func (x *InvalidateReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateReply.ProtoReflect.Descriptor instead.
func (*InvalidateReply) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{13}
}

func (x *InvalidateReply) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

type SubscriptionUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *SubscriptionUpdateData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SubscriptionUpdate) Reset() {
	*x = SubscriptionUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionUpdate) ProtoMessage() {}

func (x *SubscriptionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionUpdate.ProtoReflect.Descriptor instead.
func (*SubscriptionUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{14}
}

func (x *SubscriptionUpdate) GetData() *SubscriptionUpdateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type HandshakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerPass string `protobuf:"bytes,2,opt,name=player_pass,json=playerPass,proto3" json:"player_pass,omitempty"`
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{15}
}

func (x *HandshakeRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *HandshakeRequest) GetPlayerPass() string {
	if x != nil {
		return x.PlayerPass
	}
	return ""
}

type HandshakeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outcome *Outcome `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *HandshakeReply) Reset() {
	*x = HandshakeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeReply) ProtoMessage() {}

func (x *HandshakeReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeReply.ProtoReflect.Descriptor instead.
func (*HandshakeReply) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{16}
}

func (x *HandshakeReply) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

type NavigationUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path NavigationPath `protobuf:"varint,1,opt,name=path,proto3,enum=server.NavigationPath" json:"path,omitempty"`
}

func (x *NavigationUpdate) Reset() {
	*x = NavigationUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NavigationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationUpdate) ProtoMessage() {}

func (x *NavigationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationUpdate.ProtoReflect.Descriptor instead.
func (*NavigationUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{17}
}

func (x *NavigationUpdate) GetPath() NavigationPath {
	if x != nil {
		return x.Path
	}
	return NavigationPath_LOGIN
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mover    Mover `protobuf:"varint,1,opt,name=mover,proto3,enum=server.Mover" json:"mover,omitempty"`
	Position int32 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{18}
}

func (x *Move) GetMover() Mover {
	if x != nil {
		return x.Mover
	}
	return Mover_UNSPECIFIED
}

func (x *Move) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type MoveUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Move *Move `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
}

func (x *MoveUpdate) Reset() {
	*x = MoveUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveUpdate) ProtoMessage() {}

func (x *MoveUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveUpdate.ProtoReflect.Descriptor instead.
func (*MoveUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{19}
}

func (x *MoveUpdate) GetMove() *Move {
	if x != nil {
		return x.Move
	}
	return nil
}

type NextMoverUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mover Mover `protobuf:"varint,1,opt,name=mover,proto3,enum=server.Mover" json:"mover,omitempty"`
}

func (x *NextMoverUpdate) Reset() {
	*x = NextMoverUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextMoverUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextMoverUpdate) ProtoMessage() {}

func (x *NextMoverUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextMoverUpdate.ProtoReflect.Descriptor instead.
func (*NextMoverUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{20}
}

func (x *NextMoverUpdate) GetMover() Mover {
	if x != nil {
		return x.Mover
	}
	return Mover_UNSPECIFIED
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position int32 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{21}
}

func (x *MakeMoveRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type MakeMoveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outcome *Outcome `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *MakeMoveReply) Reset() {
	*x = MakeMoveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeMoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveReply) ProtoMessage() {}

func (x *MakeMoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveReply.ProtoReflect.Descriptor instead.
func (*MakeMoveReply) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{22}
}

func (x *MakeMoveReply) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

type CreateLobbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{23}
}

func (x *CreateLobbyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateLobbyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outcome *Outcome `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *CreateLobbyReply) Reset() {
	*x = CreateLobbyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLobbyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyReply) ProtoMessage() {}

func (x *CreateLobbyReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyReply.ProtoReflect.Descriptor instead.
func (*CreateLobbyReply) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{24}
}

func (x *CreateLobbyReply) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

type CreateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player1Id string `protobuf:"bytes,1,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player2Id string `protobuf:"bytes,2,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{25}
}

func (x *CreateGameRequest) GetPlayer1Id() string {
	if x != nil {
		return x.Player1Id
	}
	return ""
}

func (x *CreateGameRequest) GetPlayer2Id() string {
	if x != nil {
		return x.Player2Id
	}
	return ""
}

type CreateGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outcome *Outcome `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
}

func (x *CreateGameReply) Reset() {
	*x = CreateGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameReply) ProtoMessage() {}

func (x *CreateGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameReply.ProtoReflect.Descriptor instead.
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{26}
}

func (x *CreateGameReply) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

type WinnerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Winner Winner `protobuf:"varint,1,opt,name=winner,proto3,enum=server.Winner" json:"winner,omitempty"`
	Mover  Mover  `protobuf:"varint,2,opt,name=mover,proto3,enum=server.Mover" json:"mover,omitempty"`
}

func (x *WinnerUpdate) Reset() {
	*x = WinnerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WinnerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinnerUpdate) ProtoMessage() {}

func (x *WinnerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinnerUpdate.ProtoReflect.Descriptor instead.
func (*WinnerUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{27}
}

func (x *WinnerUpdate) GetWinner() Winner {
	if x != nil {
		return x.Winner
	}
	return Winner_you
}

func (x *WinnerUpdate) GetMover() Mover {
	if x != nil {
		return x.Mover
	}
	return Mover_UNSPECIFIED
}

type DrawUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DrawUpdate) Reset() {
	*x = DrawUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawUpdate) ProtoMessage() {}

func (x *DrawUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawUpdate.ProtoReflect.Descriptor instead.
func (*DrawUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{28}
}

type GameStartUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	You   Mover `protobuf:"varint,1,opt,name=you,proto3,enum=server.Mover" json:"you,omitempty"`
	Other Mover `protobuf:"varint,2,opt,name=other,proto3,enum=server.Mover" json:"other,omitempty"`
}

func (x *GameStartUpdate) Reset() {
	*x = GameStartUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStartUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartUpdate) ProtoMessage() {}

func (x *GameStartUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartUpdate.ProtoReflect.Descriptor instead.
func (*GameStartUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{29}
}

func (x *GameStartUpdate) GetYou() Mover {
	if x != nil {
		return x.You
	}
	return Mover_UNSPECIFIED
}

func (x *GameStartUpdate) GetOther() Mover {
	if x != nil {
		return x.Other
	}
	return Mover_UNSPECIFIED
}

type PlayerClientUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PlayerClientUpdate) Reset() {
	*x = PlayerClientUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_tctxto_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerClientUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerClientUpdate) ProtoMessage() {}

func (x *PlayerClientUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_tctxto_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerClientUpdate.ProtoReflect.Descriptor instead.
func (*PlayerClientUpdate) Descriptor() ([]byte, []int) {
	return file_server_tctxto_proto_rawDescGZIP(), []int{30}
}

func (x *PlayerClientUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_server_tctxto_proto protoreflect.FileDescriptor

var file_server_tctxto_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x63, 0x74, 0x78, 0x74, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xe4, 0x09,
	0x0a, 0x16, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x47, 0x0a, 0x11, 0x6e, 0x61, 0x76, 0x69,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x10, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x41, 0x0a, 0x0f, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x5f, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x48, 0x00, 0x52, 0x0e, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x10, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0f, 0x69, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x12, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x48, 0x00, 0x52, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x10, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0e, 0x6a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x14, 0x6c, 0x65, 0x61, 0x76,
	0x65, 0x5f, 0x6d, 0x79, 0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x48, 0x00, 0x52, 0x11, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x10, 0x6d, 0x79, 0x5f, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x0e, 0x6d, 0x79, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x52, 0x0a, 0x16, 0x6d, 0x79,
	0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x65,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x13, 0x6d, 0x79, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x52,
	0x0a, 0x16, 0x6d, 0x79, 0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x6c, 0x65, 0x61, 0x76, 0x65,
	0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x13, 0x6d,
	0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x45, 0x0a, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x0f, 0x6d, 0x61, 0x6b,
	0x65, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6b, 0x65,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x61, 0x6b,
	0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x6f,
	0x76, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00,
	0x52, 0x0c, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x35,
	0x0a, 0x0b, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x72, 0x61,
	0x77, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x72, 0x61, 0x77, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x67, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x11,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x4e, 0x0a, 0x14, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x12, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x1f, 0x0a, 0x1d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x5d, 0x0a,
	0x07, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x45, 0x0a, 0x05,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x22, 0x2c, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x30, 0x0a, 0x0f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x22, 0x2c, 0x0a, 0x0d, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x35, 0x0a, 0x0e, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x52, 0x05, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x22, 0x3d, 0x0a, 0x13, 0x4d, 0x79, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x26, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x3d, 0x0a, 0x13, 0x4d, 0x79, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x26,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x11, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4d,
	0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x6f,
	0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x07, 0x6f,
	0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f,
	0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x0f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x22, 0x48, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x54, 0x0a, 0x10, 0x48, 0x61,
	0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73,
	0x22, 0x3b, 0x0a, 0x0e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x22, 0x3e, 0x0a,
	0x10, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x2a, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x47, 0x0a,
	0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x6f,
	0x76, 0x65, 0x72, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x36, 0x0a, 0x0f, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f,
	0x76, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x6d, 0x6f, 0x76,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x22, 0x2d,
	0x0a, 0x0f, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a,
	0x0d, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29,
	0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f,
	0x6d, 0x65, 0x22, 0x51, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x31, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x31, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x32, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x32, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63,
	0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63,
	0x6f, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x0c, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x57, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x6d,
	0x6f, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x72,
	0x22, 0x0c, 0x0a, 0x0a, 0x44, 0x72, 0x61, 0x77, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x57,
	0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1f, 0x0a, 0x03, 0x79, 0x6f, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x03, 0x79,
	0x6f, 0x75, 0x12, 0x23, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x3d, 0x0a, 0x0e, 0x4e, 0x61, 0x76, 0x69, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47,
	0x49, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x4d, 0x59, 0x5f, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x47, 0x41, 0x4d, 0x45, 0x10, 0x03, 0x2a, 0x26, 0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x65, 0x72, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x05, 0x0a, 0x01, 0x58, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x4f, 0x10, 0x02, 0x2a, 0x1c,
	0x0a, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x07, 0x0a, 0x03, 0x79, 0x6f, 0x75, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x01, 0x32, 0xff, 0x03, 0x0a,
	0x09, 0x54, 0x69, 0x63, 0x54, 0x61, 0x63, 0x54, 0x6f, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x45, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x36, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b,
	0x65, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0a,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2e,
	0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4d, 0x79, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x0d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x08, 0x4d, 0x61, 0x6b, 0x65,
	0x4d, 0x6f, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x61,
	0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x74, 0x63, 0x74, 0x78, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_tctxto_proto_rawDescOnce sync.Once
	file_server_tctxto_proto_rawDescData = file_server_tctxto_proto_rawDesc
)

func file_server_tctxto_proto_rawDescGZIP() []byte {
	file_server_tctxto_proto_rawDescOnce.Do(func() {
		file_server_tctxto_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_tctxto_proto_rawDescData)
	})
	return file_server_tctxto_proto_rawDescData
}

var file_server_tctxto_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_server_tctxto_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_server_tctxto_proto_goTypes = []interface{}{
	(NavigationPath)(0),            // 0: server.NavigationPath
	(Mover)(0),                     // 1: server.Mover
	(Winner)(0),                    // 2: server.Winner
	(*SubscriptionUpdateData)(nil), // 3: server.SubscriptionUpdateData
	(*Empty)(nil),                  // 4: server.Empty
	(*Outcome)(nil),                // 5: server.Outcome
	(*Lobby)(nil),                  // 6: server.Lobby
	(*Player)(nil),                 // 7: server.Player
	(*ExchangeRequest)(nil),        // 8: server.ExchangeRequest
	(*ExchangeReply)(nil),          // 9: server.ExchangeReply
	(*MyLobbyDetails)(nil),         // 10: server.MyLobbyDetails
	(*MyLobbyJoinerUpdate)(nil),    // 11: server.MyLobbyJoinerUpdate
	(*MyLobbyLeaverUpdate)(nil),    // 12: server.MyLobbyLeaverUpdate
	(*LeaveMyLobbyReply)(nil),      // 13: server.LeaveMyLobbyReply
	(*JoinLobbyRequest)(nil),       // 14: server.JoinLobbyRequest
	(*JoinLobbyReply)(nil),         // 15: server.JoinLobbyReply
	(*InvalidateReply)(nil),        // 16: server.InvalidateReply
	(*SubscriptionUpdate)(nil),     // 17: server.SubscriptionUpdate
	(*HandshakeRequest)(nil),       // 18: server.HandshakeRequest
	(*HandshakeReply)(nil),         // 19: server.HandshakeReply
	(*NavigationUpdate)(nil),       // 20: server.NavigationUpdate
	(*Move)(nil),                   // 21: server.Move
	(*MoveUpdate)(nil),             // 22: server.MoveUpdate
	(*NextMoverUpdate)(nil),        // 23: server.NextMoverUpdate
	(*MakeMoveRequest)(nil),        // 24: server.MakeMoveRequest
	(*MakeMoveReply)(nil),          // 25: server.MakeMoveReply
	(*CreateLobbyRequest)(nil),     // 26: server.CreateLobbyRequest
	(*CreateLobbyReply)(nil),       // 27: server.CreateLobbyReply
	(*CreateGameRequest)(nil),      // 28: server.CreateGameRequest
	(*CreateGameReply)(nil),        // 29: server.CreateGameReply
	(*WinnerUpdate)(nil),           // 30: server.WinnerUpdate
	(*DrawUpdate)(nil),             // 31: server.DrawUpdate
	(*GameStartUpdate)(nil),        // 32: server.GameStartUpdate
	(*PlayerClientUpdate)(nil),     // 33: server.PlayerClientUpdate
}
var file_server_tctxto_proto_depIdxs = []int32{
	20, // 0: server.SubscriptionUpdateData.navigation_update:type_name -> server.NavigationUpdate
	19, // 1: server.SubscriptionUpdateData.handshake_reply:type_name -> server.HandshakeReply
	16, // 2: server.SubscriptionUpdateData.invalidate_reply:type_name -> server.InvalidateReply
	27, // 3: server.SubscriptionUpdateData.create_lobby_reply:type_name -> server.CreateLobbyReply
	15, // 4: server.SubscriptionUpdateData.join_lobby_reply:type_name -> server.JoinLobbyReply
	13, // 5: server.SubscriptionUpdateData.leave_my_lobby_reply:type_name -> server.LeaveMyLobbyReply
	10, // 6: server.SubscriptionUpdateData.my_lobby_details:type_name -> server.MyLobbyDetails
	11, // 7: server.SubscriptionUpdateData.my_lobby_joiner_update:type_name -> server.MyLobbyJoinerUpdate
	12, // 8: server.SubscriptionUpdateData.my_lobby_leaver_update:type_name -> server.MyLobbyLeaverUpdate
	29, // 9: server.SubscriptionUpdateData.create_game_reply:type_name -> server.CreateGameReply
	25, // 10: server.SubscriptionUpdateData.make_move_reply:type_name -> server.MakeMoveReply
	22, // 11: server.SubscriptionUpdateData.move_update:type_name -> server.MoveUpdate
	30, // 12: server.SubscriptionUpdateData.winner_update:type_name -> server.WinnerUpdate
	31, // 13: server.SubscriptionUpdateData.draw_update:type_name -> server.DrawUpdate
	32, // 14: server.SubscriptionUpdateData.game_start_update:type_name -> server.GameStartUpdate
	23, // 15: server.SubscriptionUpdateData.next_mover_update:type_name -> server.NextMoverUpdate
	33, // 16: server.SubscriptionUpdateData.player_client_update:type_name -> server.PlayerClientUpdate
	7,  // 17: server.Lobby.players:type_name -> server.Player
	6,  // 18: server.MyLobbyDetails.lobby:type_name -> server.Lobby
	7,  // 19: server.MyLobbyJoinerUpdate.player:type_name -> server.Player
	7,  // 20: server.MyLobbyLeaverUpdate.player:type_name -> server.Player
	5,  // 21: server.LeaveMyLobbyReply.outcome:type_name -> server.Outcome
	5,  // 22: server.JoinLobbyReply.outcome:type_name -> server.Outcome
	5,  // 23: server.InvalidateReply.outcome:type_name -> server.Outcome
	3,  // 24: server.SubscriptionUpdate.data:type_name -> server.SubscriptionUpdateData
	5,  // 25: server.HandshakeReply.outcome:type_name -> server.Outcome
	0,  // 26: server.NavigationUpdate.path:type_name -> server.NavigationPath
	1,  // 27: server.Move.mover:type_name -> server.Mover
	21, // 28: server.MoveUpdate.move:type_name -> server.Move
	1,  // 29: server.NextMoverUpdate.mover:type_name -> server.Mover
	5,  // 30: server.MakeMoveReply.outcome:type_name -> server.Outcome
	5,  // 31: server.CreateLobbyReply.outcome:type_name -> server.Outcome
	5,  // 32: server.CreateGameReply.outcome:type_name -> server.Outcome
	2,  // 33: server.WinnerUpdate.winner:type_name -> server.Winner
	1,  // 34: server.WinnerUpdate.mover:type_name -> server.Mover
	1,  // 35: server.GameStartUpdate.you:type_name -> server.Mover
	1,  // 36: server.GameStartUpdate.other:type_name -> server.Mover
	8,  // 37: server.TicTacToe.Exchange:input_type -> server.ExchangeRequest
	4,  // 38: server.TicTacToe.Subscribe:input_type -> server.Empty
	18, // 39: server.TicTacToe.Handshake:input_type -> server.HandshakeRequest
	4,  // 40: server.TicTacToe.Invalidate:input_type -> server.Empty
	26, // 41: server.TicTacToe.CreateLobby:input_type -> server.CreateLobbyRequest
	14, // 42: server.TicTacToe.JoinLobby:input_type -> server.JoinLobbyRequest
	4,  // 43: server.TicTacToe.LeaveMyLobby:input_type -> server.Empty
	28, // 44: server.TicTacToe.CreateGame:input_type -> server.CreateGameRequest
	24, // 45: server.TicTacToe.MakeMove:input_type -> server.MakeMoveRequest
	9,  // 46: server.TicTacToe.Exchange:output_type -> server.ExchangeReply
	17, // 47: server.TicTacToe.Subscribe:output_type -> server.SubscriptionUpdate
	4,  // 48: server.TicTacToe.Handshake:output_type -> server.Empty
	4,  // 49: server.TicTacToe.Invalidate:output_type -> server.Empty
	4,  // 50: server.TicTacToe.CreateLobby:output_type -> server.Empty
	4,  // 51: server.TicTacToe.JoinLobby:output_type -> server.Empty
	4,  // 52: server.TicTacToe.LeaveMyLobby:output_type -> server.Empty
	4,  // 53: server.TicTacToe.CreateGame:output_type -> server.Empty
	4,  // 54: server.TicTacToe.MakeMove:output_type -> server.Empty
	46, // [46:55] is the sub-list for method output_type
	37, // [37:46] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_server_tctxto_proto_init() }
func file_server_tctxto_proto_init() {
	if File_server_tctxto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_tctxto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionUpdateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outcome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyLobbyDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyLobbyJoinerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyLobbyLeaverUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveMyLobbyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLobbyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NavigationUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextMoverUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeMoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeMoveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLobbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLobbyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WinnerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrawUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStartUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_tctxto_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerClientUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_server_tctxto_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SubscriptionUpdateData_NavigationUpdate)(nil),
		(*SubscriptionUpdateData_HandshakeReply)(nil),
		(*SubscriptionUpdateData_InvalidateReply)(nil),
		(*SubscriptionUpdateData_CreateLobbyReply)(nil),
		(*SubscriptionUpdateData_JoinLobbyReply)(nil),
		(*SubscriptionUpdateData_LeaveMyLobbyReply)(nil),
		(*SubscriptionUpdateData_MyLobbyDetails)(nil),
		(*SubscriptionUpdateData_MyLobbyJoinerUpdate)(nil),
		(*SubscriptionUpdateData_MyLobbyLeaverUpdate)(nil),
		(*SubscriptionUpdateData_CreateGameReply)(nil),
		(*SubscriptionUpdateData_MakeMoveReply)(nil),
		(*SubscriptionUpdateData_MoveUpdate)(nil),
		(*SubscriptionUpdateData_WinnerUpdate)(nil),
		(*SubscriptionUpdateData_DrawUpdate)(nil),
		(*SubscriptionUpdateData_GameStartUpdate)(nil),
		(*SubscriptionUpdateData_NextMoverUpdate)(nil),
		(*SubscriptionUpdateData_PlayerClientUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_tctxto_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_tctxto_proto_goTypes,
		DependencyIndexes: file_server_tctxto_proto_depIdxs,
		EnumInfos:         file_server_tctxto_proto_enumTypes,
		MessageInfos:      file_server_tctxto_proto_msgTypes,
	}.Build()
	File_server_tctxto_proto = out.File
	file_server_tctxto_proto_rawDesc = nil
	file_server_tctxto_proto_goTypes = nil
	file_server_tctxto_proto_depIdxs = nil
}
